# 数据同步配置示例
# 复制此文件为 .env 并根据需要修改

# 基础服务器配置
BIND_ADDRESS=0.0.0.0:3000
ADMIN_API_KEY=your_secret_api_key_here

# 数据库配置
# 使用内存数据库（重启后数据丢失）
DATABASE_URL=sqlite::memory:

# 或使用文件数据库（数据持久化）
# DATABASE_URL=sqlite:./chat_server.db

# 连接限制
MAX_CONNECTIONS=100000

# 数据同步配置
# 外部系统回调URL（可选）
DATA_CALLBACK_URL=http://your-external-system.com/api/sync

# 定时同步间隔（秒）
# 默认300秒（5分钟），设置为0禁用定时同步
SYNC_INTERVAL_SECONDS=300

# 日志级别
RUST_LOG=chat_server=info,tower_http=info 