# 房间信息同步回调系统配置示例
# 复制此文件为 .env 并根据需要修改

# 基础服务器配置
BIND_ADDRESS=0.0.0.0:3000
ADMIN_API_KEY=your_secret_api_key_here

# 数据库配置
# 使用内存数据库（重启后数据丢失）
DATABASE_URL=sqlite::memory:

# 或使用文件数据库（数据持久化）
# DATABASE_URL=sqlite:./chat_server.db

# 连接限制
MAX_CONNECTIONS=100000

# 数据同步配置（保持向后兼容）
DATA_CALLBACK_URL=http://localhost:8080/sync/room

# 拆分后的回调URL配置
ROOM_EVENT_CALLBACK_URL=http://localhost:8080/api/room-events
CHAT_HISTORY_CALLBACK_URL=http://localhost:8080/api/chat-history
SESSION_HISTORY_CALLBACK_URL=http://localhost:8080/api/session-history
PERIODIC_SYNC_CALLBACK_URL=http://localhost:8080/api/periodic-sync

# 回调配置
CHAT_HISTORY_BATCH_SIZE=1000
SESSION_HISTORY_BATCH_SIZE=500
CHAT_HISTORY_BATCH_INTERVAL_SECONDS=300
SESSION_HISTORY_BATCH_INTERVAL_SECONDS=600

# 回调重试配置
CALLBACK_MAX_RETRIES=3
CALLBACK_RETRY_DELAY_SECONDS=5
CALLBACK_TIMEOUT_SECONDS=30

# 定时同步配置
SYNC_INTERVAL_SECONDS=300

# 日志级别
RUST_LOG=chat_server=info,tower_http=info 