# 房间信息同步回调服务器配置示例
# 将此文件重命名为 config.toml 并放在项目根目录

[server]
# 服务器监听地址
host = "127.0.0.1"
# 服务器端口
port = 3000
# 最大连接数
max_connections = 1000

[admin]
# 管理员API密钥，用于认证管理接口
api_key = "your-secret-admin-key-here"

[database]
# 数据库连接URL
url = "sqlite:data.db"

[callback]
# 数据同步回调URL - 当房间关闭时会向此URL发送房间数据
# 支持HTTP和HTTPS
data_callback_url = "http://localhost:8080/sync/room"

# 可选：回调超时设置（秒）
timeout_seconds = 30

# 可选：重试设置
max_retries = 3
retry_delay_seconds = 5

# 可选：回调认证（如果需要）
# auth_header = "Authorization: Bearer your-callback-token"

[logging]
# 日志级别: debug, info, warn, error
level = "info"
# 日志文件路径（可选）
# file = "logs/app.log" 